apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dmchk-provisor
  name: dmchk-provisor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dmchk-provisor
  template:
    metadata:
      labels:
        app: dmchk-provisor
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '3045'
    spec:
      containers:
        - image: dmchk/dmchk_microsservices:provisor-stable-b6d51285126bb338ef3a17729501120fe667a935
          name: dmchk-microsservices-pxvmm
          ports:
            - containerPort: 3045
          env:
            - name: JWT_SECRET
              value: super-secret
            - name: DATABASE_URL
              value: 'mysql://root:mysecret@mysql:3306/provisor'
            - name: PORT
              value: '3045'
          volumeMounts:
            - name: config-volume
              mountPath: /fluent-bit/etc/
        - name: fluent-bit
          image: fluent/fluent-bit:1.8
          volumeMounts:
            - name: config-volume
              mountPath: /fluent-bit/etc/
            - name: log-volume # Add this volume mount for log directory
              mountPath: /var/log/containers
          env:
            - name: FLUENT_BIT_CONFIG
              value: /fluent-bit/etc/fluent-bit-config.conf
      volumes:
        - name: config-volume
          configMap:
            name: fluent-bit-config
        - name: log-volume # Add this volume for log directory
          hostPath:
            path: /var/log/containers
