name: Continuous Integration

on: push # You can change this trigger to any other event like push, release, etc.

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build and test
        run: |
          npm install
          npm run build

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t dmchk/dmchk_microsservices:latest .
          docker push dmchk/dmchk_microsservices:latest

# Make sure to replace "your-docker-username" and "your-docker-image-name" with your actual Docker Hub username and image name.
