apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dmchk-provisor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LuizAdamchuk/dmchk-monorepo.git
    targetRevision: HEAD
    path: dmchk-provisor/k8s/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
