name: CI for Development

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

jobs:
  governance:
    name: Governance service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install packages
        working-directory: dmchk-governance
        run: npm install --prod-only # npm install --prod-only | npm ci
      - name: Formatting, linting, tsc, and tests
        working-directory: dmchk-governance
        run: |
          npm run prettier
          npm run lint
      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and push Docker image
        working-directory: dmchk-governance
        run: |
          docker build -t dmchk/dmchk_microsservices:governance-development-${{ github.sha }} .
          docker push dmchk/dmchk_microsservices:governance-development-${{ github.sha }}
  provisor:
    name: Provisor service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install packages
        working-directory: dmchk-provisor
        run: npm install --prod-only # npm install --prod-only | npm ci
      - name: Formatting, linting, tsc, and tests
        working-directory: dmchk-provisor
        run: |
          npm run prettier
          npm run lint
      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and push Docker image
        working-directory: dmchk-provisor
        run: |
          docker build -t dmchk/dmchk_microsservices:provisor-development-${{ github.sha }} .
          docker push dmchk/dmchk_microsservices:provisor-development-${{ github.sha }}
