name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  governance:
    name: Governance service
    runs-on: ubuntu-latest
    if: contains(join(github.event.commits[0].modified, ','), 'dmchk-governance')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install packages
        working-directory: dmchk-governance
        run: npm install --prod-only # npm install --prod-only | npm ci
      - name: Formatting, linting, tsc, and tests
        working-directory: dmchk-governance
        run: |
          npm run prettier
          npm run lint
      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and push Docker image
        working-directory: dmchk-governance
        run: |
          docker build -t dmchk/dmchk_microsservices:governance .
          docker push dmchk/dmchk_microsservices:governance
  provisor:
    name: Provisor service
    runs-on: ubuntu-latest
    if: contains(join(github.event.commits[0].modified, ','), 'dmchk-provisor')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install packages
        working-directory: dmchk-provisor
        run: npm install --prod-only # npm install --prod-only | npm ci
      - name: Formatting, linting, tsc, and tests
        working-directory: dmchk-provisor
        run: |
          npm run prettier
          npm run lint
      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and push Docker image
        working-directory: dmchk-provisor
        run: |
          docker build -t dmchk/dmchk_microsservices:provisor .
          docker push dmchk/dmchk_microsservices:provisor
