name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: See the folders and files
        working-directory: dmchk-governance
        run: |
          git ls-files
          git ls-tree --full-tree -r HEAD

      # - name: Build and push Docker image
      #   working-directory: dmchk-governance
      #   run: |
      #     docker build -t dmchk/dmchk_microsservices:latest .
      #     docker push dmchk/dmchk_microsservices:latest
